export type VesselPropertyTypes
    = 'none'
    | 'type'
    | 'mmsi'
    | 'callsign'
    | 'imo'
    | 'flag'
    | 'destination'
    | 'eta'
    | 'navStatus'
    | 'trackingMode'
    | 'trackingStatus'
    | 'class'
    | 'length'
    | 'beam'
    | 'draught'
    | 'boardHeight'
    | 'cog'
    | 'sog'
    | 'heading'
    | 'position';

